services:
  web:
    image: ghcr.io/kd-it/php-devcontainer/web:1728614961

    #build: docker/web
    volumes:
      - .:/app:cached
    env_file:
      - env.txt
    depends_on:
      - app
      - db
    networks:
      - app-network

  app:
    image: ghcr.io/kd-it/php-devcontainer/app:1728614960
    # build: docker/app
    env_file:
      - env.txt
    volumes:
      - .:/app:cached
      - vendor:/app/vendor
    networks:
      - app-network

  db:
    image: ghcr.io/densuke/mysql:main
    #build: db/build
    env_file:
      - env.txt
    volumes:
      - db_data:/var/lib/mysql
      - ./database-init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "/usr/local/bin/healthcheck.sh"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - app-network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network
  node:
    image: node:20-alpine  # 任意の Node.js バージョン
    container_name: node-app
    working_dir: /app
    volumes:
      - .:/app:cached
      - node_modules:/app/node_modules
    tty: true
    command: sh -c "npm install && npm run dev"
    depends_on:
      - app
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  db_data:
  vendor:
  node_modules:
  redis_data:

