# .github/workflows/laravel-ci-cd.yml

name: Laravel CI/CD - Build, Push, and Update K8s Manifests

on:
  push:
    branches: [ 永城担当 ] # CI/CDを動かしたいブランチ名

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  PHP_FPM_IMAGE_NAME: nqg1t0-laravel-app-fpm # Docker HubでのPHP-FPMイメージ名 (ユーザー名なし)
  NGINX_IMAGE_NAME: nqg1t0-nginx-web     # Docker HubでのNginxイメージ名 (ユーザー名なし)

  # --- ★★★ マニフェストリポジトリ情報 (ここは必ず自分の環境に合わせて変更！) ★★★ ---
  MANIFEST_REPO_OWNER: RyoNagashiro9280         # マニフェストリポジトリのオーナー
  MANIFEST_REPO_NAME: k8s-manifest              # マニフェストリポジトリの名前
  MANIFEST_REPO_BRANCH: main                    # マニフェストリポジトリの更新したいブランチ名
  # マニフェストリポジトリ内のHelmチャートのvalues.yamlまでのパス
  HELM_CHART_VALUES_PATH: my-nginx-chart/values.yaml

jobs:
  test-build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    outputs:
      IMAGE_TAG: ${{ steps.image_meta.outputs.IMAGE_TAG }}

    steps:
    - name: Checkout App Repository
      uses: actions/checkout@v4

    # --- (オプション) Laravelのテスト実行ステップ ---
    # (ここにテスト実行処理を追加)

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKERHUB_USERNAME }} # secrets.DOCKERHUB_USERNAME をGitHubに設定
        password: ${{ secrets.DOCKERHUB_TOKEN }}  # secrets.DOCKERHUB_TOKEN をGitHubに設定

    - name: Determine Image Tag (short SHA)
      id: image_meta
      run: |
        SHORT_SHA=$(echo ${GITHUB_SHA} | head -c7)
        echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_ENV
        echo "IMAGE_TAG=${SHORT_SHA}" >> $GITHUB_OUTPUT
        echo "Image tag will be: ${SHORT_SHA}"

    - name: Build and push PHP-FPM image
      uses: docker/build-push-action@v6
      with:
        context: . # Laravelプロジェクトのルート
        file: ./docker-prod/php-fpm/Dockerfile # PHP-FPM用Dockerfileのパス
        push: true
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.PHP_FPM_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.PHP_FPM_IMAGE_NAME }}:latest

    - name: Build and push Nginx image
      uses: docker/build-push-action@v6
      with:
        context: ./docker-prod/nginx # Nginx用Dockerfileと設定ファイルがあるディレクトリ
        file: ./docker-prod/nginx/Dockerfile # Nginx用Dockerfileのパス
        push: true
        tags: |
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.NGINX_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          ${{ env.DOCKERHUB_USERNAME }}/${{ env.NGINX_IMAGE_NAME }}:latest

  update-kubernetes-manifests:
    runs-on: ubuntu-latest
    needs: test-build-and-push

    steps:
    - name: Checkout Manifest Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ env.MANIFEST_REPO_OWNER }}/${{ env.MANIFEST_REPO_NAME }}
        token: ${{ secrets.PAT_FOR_MANIFEST_REPO }}
        ref: ${{ env.MANIFEST_REPO_BRANCH }}
        path: 'manifest-repo' # ★ここに 'manifest-repo' という名前でチェックアウト

    - name: Update Helm Chart values.yaml
      working-directory: ./manifest-repo # ★チェックアウトした manifest-repo ディレクトリに移動して作業する
      run: | # ★ yqアクションを使う代わりに、直接runでyqを実行する (yqがランナーに入ってる前提)
        echo "Attempting to update ${{ env.HELM_CHART_VALUES_PATH }} with tag ${{ needs.test-build-and-push.outputs.IMAGE_TAG }}"
        
        # HELM_CHART_VALUES_PATH は 'my-nginx-chart/values.yaml' みたいな相対パスのはず
        # working-directory が ./manifest-repo なので、その中からの相対パスで指定
        yq -i '.phpFpmImage.tag = "${{ needs.test-build-and-push.outputs.IMAGE_TAG }}"' '${{ env.HELM_CHART_VALUES_PATH }}'
        yq -i '.nginxImage.tag = "${{ needs.test-build-and-push.outputs.IMAGE_TAG }}"' '${{ env.HELM_CHART_VALUES_PATH }}'
        
        echo "Successfully updated image tags in '${{ env.HELM_CHART_VALUES_PATH }}' to ${{ needs.test-build-and-push.outputs.IMAGE_TAG }}"

    - name: Commit and Push changes to Manifest Repository
      working-directory: ./manifest-repo # ★ここも manifest-repo ディレクトリで作業
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "${{ github.actor }}@users.noreply.github.com"
        git add ${{ env.HELM_CHART_VALUES_PATH }}
        COMMIT_MSG="Update image tags to ${{ needs.test-build-and-push.outputs.IMAGE_TAG }} (triggered by ${{ github.repository }} commit ${{ github.sha }})"
        if ! git diff --cached --quiet; then
          git commit -m "$COMMIT_MSG"
          git push
        else
          echo "No changes to commit in values.yaml"
        fi


  # --- ★★★ マニフェストリポジトリの更新が必要な場合はここに追加のステップを入れる ★★★ ---